{
  "formatVersion": "1.1",
  "component": {
    "group": "com.loopnow.camera",
    "module": "initializer",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "initializer-1.0.0.jar",
          "url": "initializer-1.0.0.jar",
          "size": 3516,
          "sha512": "ab18059da2902353927b32999e93b77777a365772d8e6d87344de4fdd1e978128db92b27ac5a686a9833b92dd88fdd4c9ee55fe7e93fd8e141e2110a650b201b",
          "sha256": "ccdbaade57e49d3162dfc2435c19d742b3b38f19aef47e9f708cf2bf9feaa39c",
          "sha1": "75dbf757c490933582c5cdfae90b62e17555d6f9",
          "md5": "ec87d105a5284227d41f6f7220c9a872"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "initializer-1.0.0.jar",
          "url": "initializer-1.0.0.jar",
          "size": 3516,
          "sha512": "ab18059da2902353927b32999e93b77777a365772d8e6d87344de4fdd1e978128db92b27ac5a686a9833b92dd88fdd4c9ee55fe7e93fd8e141e2110a650b201b",
          "sha256": "ccdbaade57e49d3162dfc2435c19d742b3b38f19aef47e9f708cf2bf9feaa39c",
          "sha1": "75dbf757c490933582c5cdfae90b62e17555d6f9",
          "md5": "ec87d105a5284227d41f6f7220c9a872"
        }
      ]
    }
  ]
}
